---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: https
    port: 8443
    targetPort: 8443

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: timetagger
  name: timetagger-ingress
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
spec:
  tls:
    - hosts:
        - timetagger.punsvik.net
      secretName: timetagger-tls
  rules:
    - host: timetagger.punsvik.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  name: http
